echo "case 11"
diff /home/alexis/code/tests_sheets/cylinder/tmp/11-2D_bdr_vertices.dat /home/alexis/code/tests_sheets/cylinder/11-2D_bdr_vertices.dat
echo "case 13"
diff /home/alexis/code/tests_sheets/cylinder/tmp/13-2D_bdr_vertices.dat /home/alexis/code/tests_sheets/cylinder/13-2D_bdr_vertices.dat
echo "case 24"
diff /home/alexis/code/tests_sheets/cylinder/tmp/24-2D_bdr_vertices.dat /home/alexis/code/tests_sheets/cylinder/24-2D_bdr_vertices.dat
echo "case 35"
diff /home/alexis/code/tests_sheets/cylinder/tmp/35-2D_bdr_vertices.dat /home/alexis/code/tests_sheets/cylinder/35-2D_bdr_vertices.dat
echo "case 41"
diff /home/alexis/code/tests_sheets/cylinder/tmp/41-2D_bdr_vertices.dat /home/alexis/code/tests_sheets/cylinder/41-2D_bdr_vertices.dat
